### ISSUE TITLE
Build failed: thread 'main' panicked at 'Command failed: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:906:4

### ISSUE THREAD

**Issue by AndreKR** [meh/rust-ffmpeg#105]
I just added `ffmpeg = "0.1.1"` to my Cargo.toml and rebuilt.

I'm new to Rust, so I might be missing something obvious.

```
   Compiling ffmpeg-sys v2.8.9
error: failed to run custom build command for `ffmpeg-sys v2.8.9`
process didn't exit successfully: `C:\dev-projects\rust-test\ffmpegtest\target\debug\build\ffmpeg-sys-38b9d1a12d8b6df5\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Command failed: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:906:4
stack backtrace:
   0:        0x13f76c991 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:92
   1:        0x13f77627c - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:380
   2:        0x13f775f65 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:397
   3:        0x13f7767c5 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:577
   4:        0x13f776658 - std::panicking::begin_panic<alloc::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:538
   5:        0x13f776531 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:522
   6:        0x13f77649f - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:498
   7:        0x13f77a04e - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   8:        0x13f75b517 - core::result::unwrap_failed<std::io::error::Error>
                               at C:\projects\rust\src\libcore\macros.rs:23
   9:        0x13f75a52b - core::result::Result<std::process::ExitStatus, std::io::error::Error>::expect<std::process::ExitStatus,std::io::error::Error>
                               at C:\projects\rust\src\libcore\result.rs:799
  10:        0x13f74cdd6 - build_script_build::check_features
                               at c:\dev\rust\cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-2.8.9\build.rs:262
  11:        0x13f7513b4 - build_script_build::main
                               at c:\dev\rust\cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-2.8.9\build.rs:345
  12:        0x13f777821 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  13:        0x13f776f61 - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:52
  14:        0x13f7518e6 - main
  15:        0x13f77e6f8 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  16:         0x775b59cc - BaseThreadInitThunk

```

**Comment by retrry** [comment]
I think you should use rust-ffmpeg version from git. crates.io has only quite old version published.
